### ISSUE TITLE
多高校打卡合作邀请

### ISSUE THREAD

**Issue by mrcaidev** [kottory/NJU-health-report#10]
朋友您好！

我是[电子科技大学自动打卡](https://github.com/mrcaidev/thermoflash)项目的作者，现欲开发一款各高校通用的、基于 GitHub Actions 的自动打卡工具；目前框架与主程序都已初步搭建完毕，后续的开发者只需要编写插件即可。

一位朋友向我推荐了您的项目。拜读之后，我觉得您的代码水平与逻辑都十分地优秀且可靠，不知您是否愿意了解一下[上述的项目](https://github.com/mrcaidev/thermoflash)；如果能参与开发，更是我的荣幸。您随时可以通过 QQ 联系我：1014305148。

期待与您的合作，相互学习、共同进步！

**Comment by kottory** [comment]
首先感谢您的邀请。

健康打卡作为中国特色的大学的一种制度形式，在大部分学校都是繁琐但不可或缺的存在，否则 GitHub 上就不会如雨后春笋般涌现出如此之多的自动打卡脚本。但毕竟不是疫情初期，现如今主流高校几乎都能在 GitHub 上找到对应的自动打卡脚本实现。其中在易用性与稳定性方面自然良莠不齐，这估计也是您发起多高校健康打卡的初衷之一。

但这种 *Universal* 真的有那么容易实现嘛。自动健康打卡无非两部分流程：
1. 获取个人信息的权限（即登录）
2. 尝试给学校发送请求来模拟打卡
3. 重复 2 直到确认已经打卡成功
这部分利用 GitHub Actions 很容易实现，方便起见我们称之为“前端”。前端是基本可以拿来复用的，且实现也很简单。

与之对应的“后端”可就没那么容易了，这也是在编码。每个学校的登录方式自然各式各样，打卡方法也是五花八门。这部分不要说复用某一部分了，甚至暴露给前端的接口都很难统一。除非很高的抽象，否则后端的实现本质也只是把已有的其他学校的解决方案直接搬过来。

因此这种整合并不会给编码上解决多少困难，反而在整合的过程中制造了很多不必要的麻烦。那么在学校打卡的这个应用场景上，是否有这种放弃现有的各个学校的成熟方案，转用整合的打卡的必要呢。我认为依然意义不大。

假设打卡制度会在可见的未来都在实行着。首先，一个南京大学的学生，大概率是在几年之内都不会使用其他学校的打卡工具，自然也不会去关心其他学校的打卡，而中国大陆的高校数量很多，文档中大量的其他高校的这些信息反倒是累赘，为了大一统而实现的过度抽象势必会影响其部署这个工具。并且打卡作为灰色地带的产物，自然后端的方案可能会有变更，并且也会产生一些问题，其他学校的维护者并不能解决那个学校出现的问题。各个使用者和维护者之间并不相交，分开来是最妥当的。

因此比起开发一个给所有高校使用的打卡脚本，维护一个给自己学校使用的工具箱才是更有实际意义的做法。所以我持一个观望的态度。

**Comment by mrcaidev** [comment]
好的，感谢您的回复！
