### ISSUE TITLE
统一身份验证现在似乎必定出现验证码了

### ISSUE THREAD

**Issue by 52871299hzy** [kottory/NJU-health-report#16]

**Comment by kottory** [comment]
对。所以目前可能解决的有两种方案。

1. 存一个很久都不会过期的token
2. 用一些ocr库干碎验证码

**Comment by kottory** [comment]
似乎有人之前写过类似的脚本，https://github.com/cubiccm/NJU-Network-Authenticate。

考虑看看能不能直接拿来复用。

**Comment by psn417** [comment]
import ddddocr

def detect(auth):
    with open("code.jpg", "wb") as f:
        f.write(auth.getCaptchaCode().getbuffer())    
    ocr = ddddocr.DdddOcr()
    with open("code.jpg", 'rb') as f:
        image = f.read()
    res = ocr.classification(image)
    return res

这个包可以识别身份认证的验证码

**Comment by Kristoff-starling** [comment]
> 似乎有人之前写过类似的脚本，[https://github.com/cubiccm/NJU-Network-Authenticate。](https://github.com/cubiccm/NJU-Network-Authenticate%E3%80%82)
> 
> 考虑看看能不能直接拿来复用。

亲测可以直接复用

**Comment by kottory** [comment]
> > 似乎有人之前写过类似的脚本，[https://github.com/cubiccm/NJU-Network-Authenticate。](https://github.com/cubiccm/NJU-Network-Authenticate%E3%80%82)
> > 考虑看看能不能直接拿来复用。
> 
> 亲测可以直接复用

但是这个做法问题在于，他会引入 tensorflow 库，每次启动 Action 都会安装这个库，对于一个打卡脚本，是否有些过于重了。

所以考虑还是用 tesseract 这种比较轻的库，但这也牺牲了正确性。

上面提到了 ddddocr，不过我本机似乎没有办法安装上...有没有好心人本机测试通过并成功部署的请劳烦提一下 PR。

**Comment by EKiritsugu** [comment]
确实，刚刚也发现了。

**Comment by psn417** [comment]
> > > 似乎有人之前写过类似的脚本，[https://github.com/cubiccm/NJU-Network-Authenticate。](https://github.com/cubiccm/NJU-Network-Authenticate%E3%80%82)
> > > 考虑看看能不能直接拿来复用。
> > 
> > 
> > 亲测可以直接复用
> 
> 但是这个做法问题在于，他会引入 tensorflow 库，每次启动 Action 都会安装这个库，对于一个打卡脚本，是否有些过于重了。
> 
> 所以考虑还是用 tesseract 这种比较轻的库，但这也牺牲了正确性。
> 
> 上面提到了 ddddocr，不过我本机似乎没有办法安装上...有没有好心人本机测试通过并成功部署的请劳烦提一下 PR。

已在PR中加入ddddocr

**Comment by kottory** [comment]
已经merge了使用ddddocr的方案。目前来说是足够使用的。
