### ISSUE TITLE
要不要加个预约浴室的功能

### ISSUE THREAD

**Issue by psn417** [kottory/NJU-health-report#19]
只要加几行代码，测试过能运行
但请求的表单当中有一个值好像md5加密过，和地址有关，我只知道鼓楼的值，不知道仙林的值还是不是这个（程序里没法选别的区域）
有兴趣的话可以抓包看下

**Comment by cmj2002** [comment]
我觉得这个另开一个仓库吧，没必要放一起

**Comment by kottory** [comment]
很好奇现在这个功能还有存在的必要嘛...不都是直接进的

**Comment by psn417** [comment]
> 很好奇现在这个功能还有存在的必要嘛...不都是直接进的

鼓楼偶尔会查，不过大多数时候不查
