### ISSUE TITLE
代码更新后，如何直接更新到自己克隆的仓库呀？

### ISSUE THREAD

**Issue by Stephenluoyi** [kottory/NJU-health-report#25]
我现在只会删了重新克隆，求大佬教一下直接更新的方案

**Comment by EKiritsugu** [comment]
合并分支，就是merge一下

**Comment by kottory** [comment]
https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by Stephenluoyi** [comment]
网页上可以直接操作吗？
