### ISSUE TITLE
校园网以外的 IP 无法获取 getApplyInfoList

### ISSUE THREAD

**Issue by kottory** [kottory/NJU-health-report#28]
http://ehallapp.nju.edu.cn/xgfw/sys/yqfxmrjkdkappnju/apply/getApplyInfoList.do 无法在校园网以外的 IP 地址上打开。尚不清楚原因。

**Comment by RicoloveFeng** [comment]
是不是只要搬到git.nju就行了😭😭😭

**Comment by ytmbx** [comment]
盲猜缺header和cookie，貌似没有MOD_AUTH_CAS和_WEU这两个cookie，另外补全header后服务器不再关闭连接

**Comment by RicoloveFeng** [comment]
从@maxco2 那里偷了代码，非常感谢：https://github.com/maxco2/LoveAndPeaceReport/commit/13fa80699d669827e9e5c1733bb9ec536ed84f56

**Comment by kottory** [comment]
> 从@maxco2 那里偷了代码，非常感谢：[maxco2/LoveAndPeaceReport@13fa806](https://github.com/maxco2/LoveAndPeaceReport/commit/13fa80699d669827e9e5c1733bb9ec536ed84f56)

牛逼，不过那个unread感觉意义不大。。
