### ISSUE TITLE
获取了错误的WID

### ISSUE THREAD

**Issue by psn417** [kottory/NJU-health-report#30]
正常来说应该得到一个打卡列表信息，但实际上返回了这个：`{"code":"0","msg":"成功","data":[{"WID":"1231212123","TBZT":"1"}]}`。此处的wid是错的。

抓包后发现获取打卡列表之前多了这样一个请求：`GET /xgfw/sys/mrjkdkappnju/dist/build.js?t=1652956228820 HTTP/1.1`，其中t是个timestamp，返回了一个javascript文件，有没有人懂这个脚本干了啥？脚本在附件里。

[target.txt](https://github.com/kottory/NJU-health-report/files/8728517/target.txt)

**Comment by kottory** [comment]
发现了。这样会提示打卡成功但是事实上没有打卡上。

**Comment by Sakiyary** [comment]
更换一个ua应该就可以了

**Comment by psn417** [comment]
> 发现了。这样会提示打卡成功但是事实上没有打卡上。

那个js文件看起来像个前端框架生成的内容，估计和打卡没啥关系，可能还是别的原因吧

**Comment by RicoloveFeng** [comment]
怎么跑路了 呜呜呜😭😭
